#!/usr/bin/env python3
"""Generate the prerecorded DOCX artifact for the competitor demo run.

Run once: ``python scripts/generate_demo_artifact.py``.
The output ``data/demo/competitor_brief_notion_vs_linear.docx`` is served by
the demo route as a download so the investor sees a real artifact even
when API keys are missing.
"""

from __future__ import annotations

from pathlib import Path

from docx import Document
from docx.shared import Pt, RGBColor


def build_brief() -> Document:
    """Compose the competitive brief document."""
    doc = Document()

    title = doc.add_heading("Competitive Brief — Notion vs Linear", level=0)
    for run in title.runs:
        run.font.color.rgb = RGBColor(0x1F, 0x6F, 0xEB)

    doc.add_paragraph(
        "Generated by My Agent · Workflow: Competitor Intelligence · "
        "Runtime: ~30 seconds · Human equivalent: ~4 hours of analyst work."
    )

    doc.add_heading("Executive Summary", level=1)
    doc.add_paragraph(
        "Notion has reinforced its all-in-one workspace position with the launch "
        "of Notion AI 2.0 and three strategic acquisitions (Cron, Skiff, Flowdash) "
        "in the last 90 days. Linear retains a clear advantage on speed and "
        "opinionated workflows for product/engineering teams, but Notion is "
        "actively closing the gap on issue tracking via AI."
    )

    doc.add_heading("SWOT — Notion (target)", level=1)
    swot = doc.add_table(rows=1, cols=2)
    swot.style = "Light Grid Accent 1"
    hdr = swot.rows[0].cells
    hdr[0].text = "Strengths"
    hdr[1].text = "Weaknesses"
    row = swot.add_row().cells
    row[0].text = "Ecosystem breadth · AI integration · Strong brand"
    row[1].text = "Performance on large workspaces · Opinionated structure · Mobile UX"
    row = swot.add_row().cells
    row[0].text = "Opportunities"
    row[1].text = "Threats"
    row = swot.add_row().cells
    row[0].text = "Vertical depth (issues, roadmaps) via AI · Enterprise expansion"
    row[1].text = "Linear shipping AI roadmap · Cursor / Linear-native AI agents"

    doc.add_heading("Recommended Actions for Linear", level=1)
    actions = [
        "Double down on speed (sub-50ms interactions) as the core differentiator. "
        "Publish a public latency dashboard and benchmark vs Notion.",
        "Ship a native AI roadmap planner before Q3 to counter Notion AI 2.0 "
        "encroaching into product management.",
        "Expand integrations: Slack, GitHub, Figma — reduce switch cost for "
        "teams currently consolidating into Notion.",
    ]
    for i, action in enumerate(actions, 1):
        p = doc.add_paragraph(style="List Number")
        p.add_run(f"Action {i}: ").bold = True
        p.add_run(action)

    doc.add_heading("Sources", level=1)
    sources = [
        "Notion blog · Notion AI 2.0 launch announcement (Q1 2026)",
        "TechCrunch · Notion acquires Cron, Skiff, Flowdash",
        "LinkedIn · Notion hires ex-Figma VP Product",
        "Crunchbase · Notion at $10B post-money valuation",
        "Tavily search · 21 sources aggregated and ranked",
    ]
    for s in sources:
        doc.add_paragraph(s, style="List Bullet")

    footer = doc.add_paragraph()
    run = footer.add_run(
        "\nMy Agent · Autonomous Workflow OS · "
        "Cost of this brief: $0.42 · Time saved: 3h 58min"
    )
    run.italic = True
    run.font.size = Pt(9)
    run.font.color.rgb = RGBColor(0x6E, 0x76, 0x81)

    return doc


def main() -> int:
    """Build the demo artifact next to the run sample."""
    out_dir = Path(__file__).resolve().parent.parent / "data" / "demo"
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / "competitor_brief_notion_vs_linear.docx"
    doc = build_brief()
    doc.save(out_path)
    print(f"Wrote {out_path} ({out_path.stat().st_size} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
