import asyncio
import httpx
from docx import Document
from docx.shared import Pt, Inches, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH, WD_LINE_SPACING
from docx.oxml.ns import qn
import os

MODEL = "gemma4:e2b"
OLLAMA_URL = "http://localhost:11434"


async def chat(system: str, user: str, num_predict: int = 500) -> str:
    """Call Ollama chat API with system prompt."""
    payload = {
        "model": MODEL,
        "messages": [
            {"role": "system", "content": system},
            {"role": "user", "content": user},
        ],
        "stream": False,
        "options": {"temperature": 0.5, "num_predict": num_predict},
    }
    async with httpx.AsyncClient(timeout=120) as c:
        r = await c.post(f"{OLLAMA_URL}/api/chat", json=payload)
        data = r.json()
    return data.get("message", {}).get("content", "")


async def generate(prompt: str, num_predict: int = 500) -> str:
    """Call Ollama generate API."""
    payload = {
        "model": MODEL,
        "prompt": prompt,
        "stream": False,
        "options": {"temperature": 0.5, "num_predict": num_predict},
    }
    async with httpx.AsyncClient(timeout=120) as c:
        r = await c.post(f"{OLLAMA_URL}/api/generate", json=payload)
        data = r.json()
    return data.get("response", "")


async def generate_report_with_llm():
    """Generate report using local LLM via Ollama."""
    console_log = []
    def log(msg):
        console_log.append(msg)
        print(msg)

    log("=" * 60)
    log("ГЕНЕРАЦИЯ ДОКЛАДА ЧЕРЕЗ ЛОКАЛЬНУЮ МОДЕЛЬ (Ollama gemma4:e2b)")
    log("=" * 60)

    # Step 1: Generate outline
    log("\n[Шаг 1] Генерация плана доклада...")
    outline = await generate(
        "Create a detailed outline for a 3-page report about additive manufacturing (3D printing) in Russia. "
        "Include: 1.Introduction, 2.Current State, 3.Future Outlook, 4.Conclusion. "
        "Write in English. Keep it concise.",
        num_predict=400,
    )
    log(f"План:\n{outline[:300]}...")

    sections = []

    # Step 2: Generate each section
    prompts = [
        ("1. Introduction", 
         "Write a 150-word introduction for a report about additive manufacturing (3D printing) in Russia. "
         "Explain what 3D printing is and its importance. Write in English."),
        ("2. Current State", 
         "Write 200 words about the current state of 3D printing in Russia. "
         "Mention companies like NPO SPLIT, Rosatom, Formotrafik. Mention market size growth. "
         "Write in English."),
        ("3. Challenges and Future", 
         "Write 150 words about challenges (materials, standards, costs) and future prospects "
         "of 3D printing in Russia until 2030. Write in English."),
        ("4. Conclusion", 
         "Write a 100-word conclusion for a report about 3D printing in Russia. "
         "Summarize key points. Write in English."),
    ]

    for title, prompt in prompts:
        log(f"\n[Шаг] Генерация: {title}...")
        text = await generate(prompt, num_predict=400)
        log(f"  Получено: {len(text)} символов")
        sections.append((title, text))

    # Step 3: Build Word document
    log("\n[Шаг] Создание Word документа...")
    doc = Document()
    
    style = doc.styles['Normal']
    style.font.name = 'Times New Roman'
    style.font.size = Pt(14)
    style.element.rPr.rFonts.set(qn('w:eastAsia'), 'Times New Roman')

    # Title
    title = doc.add_heading('ADDITIVE MANUFACTURING IN THE RUSSIAN FEDERATION', level=0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    for run in title.runs:
        run.font.name = 'Times New Roman'
        run.font.size = Pt(16)
        run.font.bold = True

    # Note about generation
    note = doc.add_paragraph("[Generated by local LLM: Ollama gemma4:e2b]")
    note.alignment = WD_ALIGN_PARAGRAPH.CENTER
    note.runs[0].font.italic = True
    note.runs[0].font.size = Pt(10)
    note.runs[0].font.color.rgb = RGBColor(0x80, 0x80, 0x80)

    doc.add_paragraph()

    # Add outline
    h = doc.add_heading("Report Outline (AI-generated)", level=1)
    for run in h.runs:
        run.font.name = 'Times New Roman'
        run.font.size = Pt(14)
        run.font.bold = True
    p = doc.add_paragraph(outline)
    p.paragraph_format.line_spacing_rule = WD_LINE_SPACING.ONE_POINT_FIVE
    p.paragraph_format.first_line_indent = Inches(0.5)
    doc.add_paragraph()

    # Add sections
    for sec_title, text in sections:
        h = doc.add_heading(sec_title, level=1)
        for run in h.runs:
            run.font.name = 'Times New Roman'
            run.font.size = Pt(14)
            run.font.bold = True
        p = doc.add_paragraph(text)
        p.paragraph_format.line_spacing_rule = WD_LINE_SPACING.ONE_POINT_FIVE
        p.paragraph_format.first_line_indent = Inches(0.5)
        doc.add_paragraph()

    # Metadata
    meta = doc.add_paragraph()
    meta.add_run("---\n").font.size = Pt(10)
    meta.add_run("Generation log:\n").font.size = Pt(10)
    for line in console_log[-10:]:
        meta.add_run(line + "\n").font.size = Pt(9)
        meta.runs[-1].font.color.rgb = RGBColor(0x60, 0x60, 0x60)

    output = "output/Доклад_Аддитивные_технологии_в_РФ_LLM.docx"
    os.makedirs("output", exist_ok=True)
    doc.save(output)
    log(f"\n[OK] Сохранено: {output}")
    return output


if __name__ == "__main__":
    asyncio.run(generate_report_with_llm())
