#!/usr/bin/env python3
"""Generate prebuilt DOCX demo artifacts from sample JSON files."""

from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

DEMO_DIR = Path("data/demo")

PRESET_ARTIFACTS: dict[str, tuple[str, str]] = {
    "competitor": (
        "competitor_run_sample.json",
        "competitor_brief_notion_vs_linear.docx",
    ),
    "beauty": (
        "beauty_run_sample.json",
        "beauty_consultant_brief.docx",
    ),
    "lead": (
        "lead_run_sample.json",
        "lead_qualifier_brief.docx",
    ),
}


def _load_sample(filename: str) -> dict:
    path = DEMO_DIR / filename
    if not path.exists():
        raise FileNotFoundError(f"Demo sample missing: {path}")
    return json.loads(path.read_text(encoding="utf-8"))


def _extract_analysis(sample: dict) -> str:
    """Pull human-readable text from mock run events."""
    lines: list[str] = []
    payload = sample.get("default_payload", {})
    if payload:
        lines.append("Input payload:")
        for key, value in payload.items():
            lines.append(f"  • {key}: {value}")
        lines.append("")

    for event in sample.get("events", []):
        detail = event.get("detail", {})
        if not isinstance(detail, dict):
            continue
        output = detail.get("output")
        if isinstance(output, dict):
            if "summary" in output:
                lines.append(str(output["summary"]))
            if "swot" in output:
                swot = output["swot"]
                lines.append("SWOT:")
                for section, items in swot.items():
                    lines.append(f"  {section.title()}: {', '.join(items)}")
            if "actions" in output:
                lines.append("Recommended actions:")
                for idx, action in enumerate(output["actions"], 1):
                    lines.append(f"  {idx}. {action}")
            if "score" in output:
                lines.append(f"Lead score: {output['score']}")
            if "recommendation" in output:
                lines.append(f"Recommendation: {output['recommendation']}")
        message = detail.get("message")
        if message and event.get("event") == "completed":
            lines.append(str(message))

    summary = sample.get("summary", {})
    if summary:
        lines.append("")
        lines.append(f"Duration: {summary.get('total_duration_human', summary.get('total_duration_ms', 'n/a'))}")
        if "hours_saved" in summary:
            lines.append(f"Hours saved: {summary['hours_saved']}")

    return "\n".join(lines) if lines else "Demo report generated by My Agent."


def generate_docx(sample: dict, output_path: Path, title: str) -> None:
    """Write a DOCX file from sample data."""
    from docx import Document
    from docx.shared import Pt

    document = Document()
    heading = document.add_heading(title, level=0)
    heading.runs[0].font.size = Pt(22)

    document.add_paragraph(_extract_analysis(sample))

    output_path.parent.mkdir(parents=True, exist_ok=True)
    document.save(str(output_path))
    print(f"Generated {output_path} ({output_path.stat().st_size} bytes)")


def generate_all(force: bool = False) -> int:
    """Generate all preset DOCX artifacts. Returns count of files written."""
    count = 0
    titles = {
        "competitor": "Competitive Brief — Notion vs Linear",
        "beauty": "Beauty Consultant Brief — Salon AI Operator",
        "lead": "Lead Qualification Brief — BANT Scorecard",
    }
    for preset, (sample_file, docx_name) in PRESET_ARTIFACTS.items():
        output_path = DEMO_DIR / docx_name
        if output_path.exists() and not force:
            print(f"Skip existing {output_path}")
            continue
        sample = _load_sample(sample_file)
        generate_docx(sample, output_path, titles[preset])
        count += 1
    return count


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="Generate demo DOCX artifacts")
    parser.add_argument("--force", action="store_true", help="Overwrite existing files")
    args = parser.parse_args()
    written = generate_all(force=args.force)
    print(f"Done: {written} artifact(s) generated")
